version: '3'

services:
  soketi:
    restart: always
    image: quay.io/soketi/soketi:latest-16-alpine
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      SOKETI_DEFAULT_APP_ID: developerlocalappid
      SOKETI_DEFAULT_APP_KEY: localws
      SOKETI_DEFAULT_APP_SECRET: thisisasecret
      SOKETI_DEFAULT_APP_USER_AUTHENTICATION: "true"

  db:
    image: postgres:15.3-alpine
    container_name: leaderboard-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: leaderboard_db_2
    ports:
      - "54322:5432"
    volumes:
      - /Users/zehrademirhan/Desktop/docker_local_services/dbdata:/var/lib/postgresql/data

  redis-node-1:
    image: redis:7-alpine
    container_name: leaderboard-redis-node-1
    command: >
      redis-server --port 7001
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --cluster-announce-ip redis-node-1
                   --appendonly yes
    ports:
      - "7001:7001"
    volumes:
      - redis-node-1-data:/data

  redis-node-2:
    image: redis:7-alpine
    container_name: leaderboard-redis-node-2
    command: >
      redis-server --port 7002
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --cluster-announce-ip redis-node-2
                   --appendonly yes
    ports:
      - "7002:7002"
    volumes:
      - redis-node-2-data:/data

  redis-node-3:
    image: redis:7-alpine
    container_name: leaderboard-redis-node-3
    command: >
      redis-server --port 7003
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --cluster-announce-ip redis-node-3
                   --appendonly yes
    ports:
      - "7003:7003"
    volumes:
      - redis-node-3-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: leaderboard:latest
    container_name: leaderboard-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      REDIS_URL: redis://redis-node-1:7001
    depends_on:
      - db
      - redis-node-1
      - redis-node-2
      - redis-node-3

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
